import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import LandingPage from "@/components/landingPage/landingPage";
import { useGetAccountTestRQuery } from "@/redux/services/api";

export default function Home() {
  const { data, isLoading, isError, error } = useGetAccountTestRQuery();

  isError ?? console.log("from main", error);
  return (
    <>
      <Head>
        <title>BST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPage></LandingPage>
    </>
  );
}
